services:
  service-nginx:
    image: nginx:latest
    container_name: service-nginx
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ${VPS_CONFIG_DIR}/nginx/static:/static
      - ${VPS_CONFIG_DIR}/nginx/config:/etc/nginx/conf.d
      - ${VPS_CONFIG_DIR}/nginx/logs:/var/log/nginx
      - ${VPS_SSL_CERTS_DIR}:/ssl_certs
    restart: always
    networks:  
      - work-network

  service-sing-box:  
    build: .
    container_name: service-sing-box
    restart: always
    ports:
      - "443:443"
    volumes:
      - ${VPS_CONFIG_DIR}/sing-box:/etc/sing-box
      - ${VPS_SSL_CERTS_DIR}:/ssl_certs
    networks:  
      - work-network
    depends_on:
      - service-nginx


networks:
  work-network:
    driver: bridge